// This file is automatically generated. Do not modify it manually.

package main

import (
	"strings"

	"github.com/mattermost/mattermost-server/v5/model"
)

var manifest *model.Manifest

const manifestStr = `
{
  "id": "io.goscrum.mattermost-bot",
  "name": "GoScrum Bot",
  "description": "GoScrum Bot.",
  "version": "0.1.0",
  "min_server_version": "5.12.0",
  "server": {
    "executables": {
      "linux-amd64": "server/dist/plugin-linux-amd64",
      "darwin-amd64": "server/dist/plugin-darwin-amd64",
      "windows-amd64": "server/dist/plugin-windows-amd64.exe"
    },
    "executable": ""
  },
  "webapp": {
    "bundle_path": "webapp/dist/main.js"
  },
  "settings_schema": {
    "header": "",
    "footer": "",
    "settings": [
      {
        "key": "ZoomURL",
        "display_name": "Zoom URL",
        "type": "text",
        "help_text": "The URL for a self-hosted private cloud or on-premise Zoom server. For example, https://yourzoom.com. Leave blank if you're using Zoom's vendor-hosted SaaS service.",
        "placeholder": "https://zoom.us",
        "default": null
      },
      {
        "key": "ZoomAPIURL",
        "display_name": "Zoom API URL",
        "type": "text",
        "help_text": "The API URL for a self-hosted private cloud or on-premise Zoom server. For example, https://api.yourzoom.com/v2. Leave blank if you're using Zoom's vendor-hosted SaaS service.",
        "placeholder": "https://api.zoom.us/v2",
        "default": null
      },
      {
        "key": "APIKey",
        "display_name": "API Key",
        "type": "text",
        "help_text": "The API Key generated by Zoom, used to create meetings and pull user data.",
        "placeholder": "",
        "default": null
      },
      {
        "key": "APISecret",
        "display_name": "API Secret",
        "type": "text",
        "help_text": "The API Secret generated by Zoom for your API key.",
        "placeholder": "",
        "default": null
      },
      {
        "key": "WebhookSecret",
        "display_name": "Webhook Secret",
        "type": "generated",
        "help_text": "The secret used to authenticate the webhook to Mattermost.",
        "regenerate_help_text": "Regenerates the secret for the webhook URL endpoint. Regenerating the secret invalidates your existing Zoom plugin.",
        "placeholder": "",
        "default": null
      }
    ]
  }
}
`

func init() {
	manifest = model.ManifestFromJson(strings.NewReader(manifestStr))
}
